this version of S91g_ether specific for wb40n
git-svn-id: svn://10.1.10.7/dev_linux/wb/trunk@18500 ce631cd2-4ded-b346-a5c6-2b5c1f60751c

diff --git a/buildroot/board/sdc/wb40n/rootfs-additions/etc/init.d/opt/S91g_ether b/buildroot/board/sdc/wb40n/rootfs-additions/etc/init.d/opt/S91g_ether
--- a/buildroot/board/sdc/wb40n/rootfs-additions/etc/init.d/opt/S91g_ether
+++ b/buildroot/board/sdc/wb40n/rootfs-additions/etc/init.d/opt/S91g_ether
@@ -1,7 +1,8 @@
 #!/bin/sh
-# g_ether
-# this init only loads/unloads the hw-phy driver for a usb interface
-# configuration is handled via helpers in /etc/network
+# g_ether - init for wb40n
+#
+# This init only loads/unloads the hw-phy driver for a usb interface.
+# Configuration is handled via helpers in /etc/network, see /e/n/i file.
 
 
 # the expected iface name
@@ -9,13 +10,12 @@ USB_IF=usb0
 
 # arg1 is device name
 # arg2 is deciseconds
-checkinterface()
-{
+checkinterface() {
   decisec='busybox usleep 100000'
   let x=0
   while [ $x -lt $2 ]
   do
-    grep -o $1 /proc/net/dev 2>/dev/null && break
+    grep -o "$1" /proc/net/dev 2>/dev/null && break
     echo -en . && $decisec && let x+=1
   done
   [ $x -ge $2 ] && return 1 || return 0
@@ -31,12 +31,9 @@ start() {
   # find the just created interface name
   #for dev in `ls -td /sys/class/net/usb[0-9] 2>/dev/null`; do echo ${dev##*/} && break; done  
   
-  # maybe wait a bit for the interface
-#  if ! grep -o $USB_IF /proc/net/dev
-#  then
-    checkinterface $USB_IF 12 \
-    || { echo -e "\n  ...driver error, interface $USB_IF is not usable"; exit 1; }
-#  fi
+  # await upto 1.2s for the interface
+  checkinterface $USB_IF 12 \
+  || { echo -e "\n  ...driver error, interface '$USB_IF' is not usable"; exit 1; }
 }
 
 stop() {
