reworked proftpd init to allow working with inetd or standalone
git-svn-id: svn://10.1.10.7/dev_linux/wb/trunk@19352 ce631cd2-4ded-b346-a5c6-2b5c1f60751c

diff --git a/buildroot-patches/buildroot-2013.02-laird1.patch b/buildroot-patches/buildroot-2013.02-laird1.patch
--- a/buildroot-patches/buildroot-2013.02-laird1.patch
+++ b/buildroot-patches/buildroot-2013.02-laird1.patch
@@ -778,6 +778,101 @@ diff -Naur old/package/proftpd/proftpd.mk new/package/proftpd/proftpd.mk
  	rm -f $(TARGET_DIR)/etc/proftpd.conf
  endef
  
+diff -Naur old/package/proftpd/S50proftpd new/package/proftpd/S50proftpd
+--- old/package/proftpd/S50proftpd	2013-04-22 23:49:34.941440166 +0100
++++ new/package/proftpd/S50proftpd	2013-05-09 10:52:16.741777628 -0500
+@@ -1,46 +1,58 @@
+ #!/bin/sh 
++# proftpd - ftp daemon init-script
++# supports inetd and pre-checking configuration
+ 
+-DAEMON=/usr/sbin/proftpd
+ trap "" 1
+ trap "" 15
+-test -f $DAEMON || exit 0
+ [ ! -d /var/run/proftpd ] && mkdir /var/run/proftpd
+ [ ! -f /var/log/wtmp ] && touch /var/log/wtmp
+ 
+-start() {
+-	echo -n "Starting ProFTPD: "
+-	$DAEMON
+-	if [ $? != 0 ]; then
+-		echo "FAILED"
+-		exit 1
+-	else
+-		echo "done"
+-	fi
+-}
+-
+-stop() {
+-	echo -n "Stopping ProFTPD: "
+-	killall proftpd
+-        echo "done"
++pre_check() {
++  [ -s /etc/proftpd.conf ] \
++  || { on_error="config missing"; return 1; }
++  
++  if [ -z "$inetd_" ]
++  then
++    # set ServerType to "standalone" if necessary
++    sed '/^ServerType[\t ]*inetd/s/inetd/standalone/' -i /etc/proftpd.conf
++  else
++    # set ServerType to "inetd" if necessary
++    sed '/^ServerType[\t ]*standalone/s/standalone/inetd/' -i /etc/proftpd.conf
++  fi
+ }
+ 
+ case "$1" in
+-    start)
+-	start
+-	;;
+-
+-    stop)
+-	stop
+-	;;
+-
+-    restart)
+-    	stop
+-    	start
+-	;;
+-
+-    *)
+-	echo "Usage: /etc/init.d/S50proftpd {start|stop|restart}"
+-	exit 1
++  stop)
++    echo -n "Stopping ProFTPD: "
++    killall proftpd 2>/dev/null
++    echo "OK"
++    ;;
++
++  start)
++    echo -n "Starting ProFTPD: "
++    [ -z "$rcS_" ] && pre_check
++    /usr/sbin/proftpd
++    if [ $? != 0 ]
++    then
++      echo "FAILED ${on_error:+- $on_error}"
++      false
++    else
++      echo "OK"
++    fi
++    ;;
++
++  restart)
++    $0 stop
++    $0 start
++    ;;
++
++  check)
++    pre_check
++    ;;
++  
++  *)
++    echo "Usage: $0 {stop|start|restart}"
++    false
+ 	;;
+ esac
+ 
 diff -Naur old/package/regulatory/Config.in new/package/regulatory/Config.in
 --- old/package/regulatory/Config.in	1970-01-01 01:00:00.000000000 +0100
 +++ new/package/regulatory/Config.in	2013-04-22 21:36:40.000000000 +0100
