fw_select v20130309 + added check for platform updated_% + improve platform checking + improve testmode checking + added option --loglevel + updated usage info and comments   ...and point out that askerisk is not literal to an option + move cp_dprf() inside transfer_system_settings()   ...and changd copy method to use tar|tar + added ask() as a prompting wrapper to read builtin
git-svn-id: svn://10.1.10.7/dev_linux/wb/trunk@18730 ce631cd2-4ded-b346-a5c6-2b5c1f60751c

diff --git a/buildroot/board/sdc/rootfs-additions-common/usr/sbin/fw_select b/buildroot/board/sdc/rootfs-additions-common/usr/sbin/fw_select
--- a/buildroot/board/sdc/rootfs-additions-common/usr/sbin/fw_select
+++ b/buildroot/board/sdc/rootfs-additions-common/usr/sbin/fw_select
@@ -2,8 +2,9 @@
 # FirmWare Select Utility for WB40NBT/WB45NBT Linux
 # Jon Hefling, jon.hefling@lairdtech.com, 29-Jun'12
 #
-VERSION=20130211
+VERSION=20130309
 SELF=${0##*/}
+TM_FILE=/etc/default/$SELF.test
 
 # alternate rootfs
 ALT_ROOTFS_MOUNT=/mnt/alt_rootfs
@@ -12,8 +13,8 @@ ALT_ROOTFS_LOCK=/tmp/alt_rootfs.lock
 show_usage_info() {
   cat <<__End-Of-Usage-Info-Block
 This utility is mainly useful to:
-  a.) manually set the kernel-a/b and/or rootfs-a/b ...to use upon boot
-  Usage: [kernel|rootfs]-<ab>
+  a.) Manually set the kernel-a/b and/or rootfs-a/b ...to use upon boot
+  Usage: [kernel|rootfs]-{a|b}
   Example: to see the current settings
   # $SELF
   Example: to set rootfs-b
@@ -21,7 +22,7 @@ This utility is mainly useful to:
   Example: to set both kernel-a and rootfs-a
   # $SELF -a
      
-  b.) copy select files from the alternate rootfs to the current rootfs-a/b
+  b.) Copy select files from the alternate rootfs to the current rootfs-a/b
   Without given arg, files from alternate rootfs are copied, if via rcS. 
   With 'access' to mount/umount alternate rootfs.
   With 'export' to push from the current to the alternate rootfs.
@@ -30,7 +31,7 @@ This utility is mainly useful to:
   Example: to pull items from previously used rootfs
   # $SELF --transfer import
   
-  c.) restore default bootcmd and bootargs via u-boot image
+  c.) Restore default bootcmd and bootargs via u-boot image
   Without given arg, just restore bootcmd, bootargs and any dependent variables.
   With '...' the extracted defaults are also displayed.
   With 'erase' the u-boot_env is erased, and upon reboot, all defaults restored.
@@ -38,30 +39,19 @@ This utility is mainly useful to:
   Example: to restore bootargs
   # $SELF --default
 
-  d.) show details of active partition-map, and u-boot_env
+  d.) Set the loglevel value in bootargs
+  Without given value, then default value is used.
+  Usage: --loglevel=N
+  
+  e.) Show details of active partition-map, and u-boot_env
   Usage: --show
+  
 __End-Of-Usage-Info-Block
 }
 
-
-msg() {
-  if ! ls -d /lib/modules/`uname -r` >/dev/null 2>&1
-  then
-    echo "currently mismatched:"
-    echo "  kernel - `uname -r`"
-    echo "  rootfs - `ls -d /lib/modules/* |cut -f4 -d/`"
-    echo
-  fi
-  echo -e $wb ${tm:++tm} $@
-}
-
-exit_error() {
-  [ -n "$1" ] && echo -e \ \ ..."$@" >/dev/stderr
-  exit 1
-}
-
-# if the following file exists, then set testmode
-[ -f /etc/default/$SELF.test ] && tm=echo || tm=
+# set testmode if the TM_FILE exists                                     
+test -f "$TM_FILE" && tm=echo\ -e || tm=                   
+grep -sq verbose "$TM_FILE" && set -x   
 
 # set some commands in testmode so won't do any writes
 cp=$tm\ cp
@@ -69,41 +59,33 @@ reboot=$tm\ reboot
 flash_erase=$tm\ flash_erase
 fw_setenv=$tm\ fw_setenv
 fw_printenv=fw_printenv 
-if ! fw_printenv >/dev/null
+if ! $fw_printenv >/dev/null
 then
-  [ -f /etc/fw_env.config ] || echo "fw_env.config missing"
-  exit 1
+  test -f /etc/fw_env.config || echo "  ...missing: /etc/fw_env.config"
+  ${tm:-exit 1}
 fi
 
-# ensure this is the expected embedded architecture
-if ! grep -q ARM926 /proc/cpuinfo \
-&& [ -z "$tm" ]
-then
-  exit_error "script is for embedded Linux platforms only"
-fi
- 
-# check description of machine: <string>
+rm -f /tmp/incompatible_u-boot_env
+
+eval $( $fw_printenv -n updated_% 2>/dev/null \
+      |grep -oE "at91bs=.|u_boot=.|kernel=.|rootfs=." )
+
+# check description of machine: <string> and determine settings
 md=$( sed -n 's/Hardware.*: \(.*\)/\1/p' /proc/cpuinfo )
 case $md in
-  'Workgroup Bridge 40N'*) ## arch/arm/mach-at91/board-wb40n.c
+  'Workgroup Bridge 40N'*) ### arch/arm/mach-at91/board-wb40n.c
     wb=wb40nbt
     ;;
-  'Workgroup Bridge 45N'*) ## arch/arm/mach-at91/board-dt.c
-    wb=wb45nbt
-    ;;                                             
-  'Atmel AT91SAM (Device Tree)') ## arch/arm/mach-at91/board-dt.c (depreciated)
+  'Workgroup Bridge 45N'*) ### arch/arm/mach-at91/board-dt.c
     wb=wb45nbt
     ;;
-  *)
-    [ -z "$tm" ] \
-    && exit_error "unsupported: $md"
+  *) ### unknown architecture...
+    grep -e ^Processor -e ^Hardware /proc/cpuinfo
+    echo "  ...unsupported"
+    ${tm:-exit 1}
     fw_printenv=$tm\ $fw_printenv
     ;;
 esac
-
-# default console and loglevel settings
-#CONSOLE='console=ttyS0,115200 loglevel=4'
-
 case $wb in
   wb40n*) ### settings for imageset a/a, add to get b/b
     UBM=0x21000000
@@ -111,8 +93,6 @@ case $wb in
     KIA=0x000a0000
     KIP=3
     RIP=5
-    #BA_=$CONSOLE\ 'mem=32M rw rootfstype=ubifs root=ubi0:rootfs ubi.mtd=5'
-    #BC_='bootm'
     ;;
   wb45n*) ### settings for imageset a/a, add to get b/b
     UBM=0x22000000
@@ -120,12 +100,14 @@ case $wb in
     KIA=0x000e0000
     KIP=4
     RIP=6
-    #BA_=$CONSOLE\ 'mem=64M noinitrd rw rootfstype=ubifs root=ubi0:rootfs ubi.mtd=6'
-    #BC_='run _mtd; bootm'
     ;;
 esac
- 
-# special functions can process arithimetic expressions
+
+ask() { eval ${@##* }=; read "$@"; usleep 200000; echo -en \\033[1K\\r; }
+
+exit_error() { [ -n "$1" ] && echo -e \ \ ..."$@" >&2; exit 1; }
+
+# special functions to evaluate arithimetic expressions
 iszero() { ! let ${1:-0} && return 0 || return 1; }
 hexify() { let x=${1:-0}; printf "0x%08x" $x; }
 
@@ -147,7 +129,7 @@ bootcmd_x() {
   || [ $BC_kia != $KIA -a $BC_kia != $( hexify  $KIA+$KIS ) ]
   then
     [ "auto" == "$1" ] && return 0
-    echo "  ...incompatible bootcmd set in u-boot_env" >/dev/stderr
+    echo "  ...incompatible bootcmd set in u-boot_env" >&2
     touch /tmp/incompatible_u-boot_env
     BC_kia=$( hexify )
     return 1
@@ -162,7 +144,7 @@ bootargs_x() {
   if [ -z "$BA_mtd" ]
   then
     [ "auto" == "$1" ] && return 0
-    echo "  ...incompatible bootargs set in u-boot_env" >/dev/stderr
+    echo "  ...incompatible bootargs set in u-boot_env" >&2
     touch /tmp/incompatible_u-boot_env
     BA_mtd=0
     return 1
@@ -197,50 +179,35 @@ rootfs_x() {
   sed -n 's/.*ubi.mtd=\(.\).*/\1/p' /proc/cmdline
 }
 
-show_current_settings() {
-  echo "set to use upon boot:"
+current_configuration() {
+  echo $wb - $( cat /etc/*-release 2>/dev/null )
+  iszero `rootfs_x`-$RIP && ab=a || ab=b
+  echo " -> `uname -nr` on rootfs-$ab"
+  echo "     ...mismatched kernel: `ls -d /lib/modules/*`" |grep -v `uname -r`
+  echo
+  grep -qs $ALT_ROOTFS_MOUNT /proc/mounts \
+  && echo -e "$ALT_ROOTFS_MOUNT is accessible\n"
+  if [ -n "$at91bs$u_boot$rootfs$kernel" ]
+  then
+    echo -e "updated_%" \
+         "${at91bs:+\n  at91bs}" \
+         "${u_boot:+\n  u_boot}" \
+         "${kernel:+\n  kernel-${kernel}}" \
+         "${rootfs:+\n  rootfs-${rootfs}}" \
+         "\n"
+  fi
+  echo "bootup:"
   echo "  kernel-`kernel_ab`"
   echo "  rootfs-`rootfs_ab`"
 }
 
 alt_rootfs() {
-  # arg1 is mount or unmount
+  iszero `rootfs_x`-$RIP && let rip=$RIP+1 || let rip=$RIP 
   #
- if [ $RIP -eq `rootfs_x` ]
-  then
-    let rip=$RIP+1
-  else
-    let rip=$RIP
-  fi
+  # args: <un/mount>
   case $1 in
     '') # indicate alt_rootfs is a/b
       iszero $rip-$RIP && echo a || echo b
-      ;;
-
-    m*) # try to mount 
-      if [ -f $ALT_ROOTFS_LOCK ]
-      then
-        #ubinfo /dev/`cat $ALT_ROOTFS_LOCK`
-        mount |grep `cat $ALT_ROOTFS_LOCK` 2>/dev/null
-        echo
-        echo "  alt_rootfs-`alt_rootfs` is already attached/mounted"
-        echo "  ...try: '--transfer access off'"
-        return 0
-      fi
-      mkdir -p $ALT_ROOTFS_MOUNT
-      n=$( ubiattach -p /dev/mtd${rip} |sed 's/.*ice number \([123]\).*/\1/' )
-      if ubinfo /dev/ubi${n} |grep -q "^Present"
-      then
-        # expecting to mount volume_0 of newly attached ubi device n
-        mount -t ubifs /dev/ubi${n}_0 $ALT_ROOTFS_MOUNT \
-        && echo /dev/mtd${rip} mounted at $ALT_ROOTFS_MOUNT \
-        && echo ubi${n} >$ALT_ROOTFS_LOCK \
-        && return 0
-      fi
-      echo unable to mount /dev/mtd${rip}
-      ubidetach -p /dev/mtd${rip}
-      rmdir $ALT_ROOTFS_MOUNT
-      return 1
       ;;
 
     u*) # try to unmount
@@ -250,57 +217,85 @@ alt_rootfs() {
         ubidetach -p /dev/mtd${rip}
         rmdir $ALT_ROOTFS_MOUNT
         rm -f $ALT_ROOTFS_LOCK
-        echo $ALT_ROOTFS_MOUNT unmounted
+        echo \ \ $ALT_ROOTFS_MOUNT unmounted
       fi
       return 0
+      ;;
+
+    m*) # try to mount 
+      if [ -f $ALT_ROOTFS_LOCK ]
+      then
+        echo "alt_rootfs-`alt_rootfs` is already attached/mounted"
+        #ubinfo /dev/`cat $ALT_ROOTFS_LOCK`
+        mount |grep `cat $ALT_ROOTFS_LOCK` 2>/dev/null
+        echo "  ...try: '--transfer access off'"
+        return 0
+      fi
+      mkdir -p $ALT_ROOTFS_MOUNT
+      n=$( ubiattach -p /dev/mtd${rip} |sed 's/.*ice number \([123]\).*/\1/' )
+      if ubinfo /dev/ubi${n} |grep -q "^Present"
+      then
+        # expecting to mount volume_0 of newly attached ubi device n
+        mount -t ubifs /dev/ubi${n}_0 $ALT_ROOTFS_MOUNT \
+        && echo mounted /dev/mtd${rip} at $ALT_ROOTFS_MOUNT \
+        && echo ubi${n} >$ALT_ROOTFS_LOCK \
+        && return 0
+      fi
+      echo unable to mount /dev/mtd${rip}
+      ubidetach -p /dev/mtd${rip}
+      rmdir $ALT_ROOTFS_MOUNT
+      return 1
       ;;
   esac
 }
 
-cp_dprf() { $cp -af $1 $2 2>/dev/null && echo "copied $1 -> $2"; }
-
 transfer_system_settings() {
-  # arg1 is source
-  # arg2 is target
-  #
   alt_rootfs m || return 1
-  cp_dprf ${1}etc/summit/profiles.conf ${2}etc/summit
-  cp_dprf ${1}etc/random-seed ${2}etc
-  cp_dprf ${1}etc/ssl/certs ${2}etc/ssl
-  cp_dprf ${1}etc/ssh ${2}etc
-  cp_dprf ${1}root/.ssh ${2}root
-  echo okay...
+  test $1 == -v && { shift; echo transferring system settings; }
+  test $1 != / && echo copying from $1 || echo copying to $2
+  #
+  # args: <source> <target> <path/file>
+  cp_dprf() \
+    { tar -c -C $1 ${3#/} |tar -xv -C $2 |sed 's/^/  \//'; }
+  #
+  cp_dprf $1 $2 /etc/summit/profiles.conf
+  cp_dprf $1 $2 /etc/random-seed
+  cp_dprf $1 $2 /etc/ssl/certs
+  cp_dprf $1 $2 /etc/ssh
+  cp_dprf $1 $2 /root/.ssh
   alt_rootfs u
   return 0
 }
 
 
-rm -f /tmp/incompatible_u-boot_env
+# main
 case $1 in
-
-  --transfer*) ## copy select files from/to alt-rootfs '--transfer help'
+  --transfer*) ## copy from/to alt-rootfs '--transfer help'
     if bootcmd_x
     then
       case $2 in
         access) # make the alternate rootfs accessible or not [<off>]
           [ "off" != "$3" ] && alt_rootfs m || alt_rootfs u
           ;;
-        export|push|store) # push select files to alternate rootfs
+        export|push) # push select files to alternate rootfs
           transfer_system_settings / $ALT_ROOTFS_MOUNT/
           ;;
-        import|pull|recall) # pull select files to current rootfs
+        import|pull) # pull select files to current rootfs
           transfer_system_settings $ALT_ROOTFS_MOUNT/ /
           ;;
-        '') # assume 'pull' in lieu of given arg and via rcS
-          [ -n "$rcS_" ] \
-          && transfer_system_settings $ALT_ROOTFS_MOUNT/ /
+        '') # assume 'push/pull' based on rule
+          [ -n "$rcS_" ] && transfer_system_settings -v $ALT_ROOTFS_MOUNT/ /
+          [ -n "$rootfs" ] && transfer_system_settings -v / $ALT_ROOTFS_MOUNT/
+          let $? && exit_error
           ;;
         *) # show relevant usage/help 
           echo "This option allows copying standard settings, profiles, certs and keys,"
           echo "  between the two root-filesystems."
+          echo
           echo "Use 'import' to copy from the other filesystem to the current filesystem."
           echo "Use 'export' to copy from the current filesystem to the other filesystem."
           echo "Use 'access [off]' to just u/mount the other filesystem at $ALT_ROOTFS_MOUNT."
+          echo
           echo "Usage:"
           echo "  $SELF --transfer {import|export|access [off]}"
           ;;
@@ -308,30 +303,42 @@ case $1 in
     fi
     ;;
 
-  --default*) ## restore u-boot_env default variables '--default help'
+  --loglevel*) ## restore or set new value '--loglevel=N'
+    test -n "${1:11}" \
+    && eval ${1:2} \
+    || eval `nanddump --bb=skipbad --omitoob --quiet /dev/mtd1 2>/dev/null |strings |grep -m1 -o loglevel=.`
+    # set loglevel with given value or default value or assume '4'
+    bootargs=$( $fw_printenv -n bootargs \
+              |sed "s/loglevel=./loglevel=${loglevel:-4}/" )
+    $fw_setenv bootargs $bootargs \
+    && echo set loglevel=${loglevel:-4}
+    ;;
+    
+  --default*) ## restore u-boot_env variables '--default help'
     case $2 in
       erase) # set all defaults by erasing u-boot_env
-        msg erasing u-boot_env to restore defaults, then will reboot
+        echo erasing u-boot_env to restore defaults, then will reboot
         $fw_printenv ethaddr 2>/dev/null \
           |sed 's/.*/warning: this will remove the current &/;s/=/ /'
-        read -t5 -n1 -s -p "  Are you sure? [y/N ...5s]" a
-        echo -en \\033[1K\\r
+        #
+        ask -t5 -n1 -p"  Are you sure? [y/N ...5s]" -s a
         [ "$a" != "y" ] && exit_error aborted
         case $wb in
-          wb40*)
+          wb40*) ### erase
             $flash_erase -q /dev/mtd2 0 0
             ;;
-          wb45*)
+          wb45*) ### erase procedure for redundant u-boot_env
             $flash_erase -q /dev/mtd3 0 0 && $flash_erase -q /dev/mtd2 0 0
             ;;
         esac
         [ $? -eq 0 ] && $reboot || exit_error "failed to erase u-boot_env"
         ;;
       ''|...) # set default bootcmd, bootargs and dependent vars by reading u-boot image
-        msg reading /dev/mtd1
-        nanddump -q /dev/mtd1 2>/dev/null |strings |sed '/udrate=/,/udrate=/!d' >/tmp/u-boot
+        echo reading /dev/mtd1
+        nanddump --bb=skipbad --omitoob --quiet /dev/mtd1 |strings \
+        |sed '/audrate=/,/audrate=/!d' >/tmp/u-boot
         [ -f /tmp/u-boot ] \
-        || exit_error "cannot read u-boot image at /dev/mtd1"
+        || exit_error "unable to get default settings from image at /dev/mtd1"
         [ "..." == "$2" ] \
         && echo -e "\nu-boot: (defaults)\n`sed -n '2,$p' /tmp/u-boot`\n"
         echo restoring...
@@ -350,26 +357,28 @@ case $1 in
         ;;
       *) # show relevant usage/help
         echo "This option allows restoring u-boot_env bootcmd and bootargs."
-        echo "The defaults are extracted from the u-boot binary image."
+        echo "  (the defaults are extracted from the u-boot binary image)"
+        echo
         echo "Use '...' to also see the defaults from the image."
         echo "Use 'erase' to completely restore all of u-boot_env to defaults."
+        echo
         echo "Usage:"
         echo "  $SELF --default [...|erase]"
         ;;
     esac
     ;;
 
-  --usage) ## detailed usage info and a few examples
-    $0 -h
+  --usage) ## see detailed usage info and a few examples
     show_usage_info
+    exec $0 -h
     ;;
 
   --show) ## details of active partition map, and u-boot_env
-    msg active partitions:
+    echo active partitions:
     let kip=0 #+`kernel_x`
     let rip=0+`rootfs_x`
     let addr=0
-    echo " mtd     address     size      description"
+    echo "  mtd     address     size      description"
     for x in `grep -l nand /sys/class/mtd/*/type`
     do
       mtd=${x%%/type}
@@ -377,7 +386,7 @@ case $1 in
       let size=`cat $mtd/size`
       mtd=${mtd##/sys/class/mtd/mtd}
       [ $mtd -gt 0 -a $mtd -eq $kip -o $mtd -eq $rip ] && ap='->' || ap='  ' 
-      printf "%s% 2d:  0x%08x  0x%08x  %s\n" "$ap" $mtd $addr $size "$name"
+      printf " %s% 2d:  0x%08x  0x%08x  %s\n" "$ap" $mtd $addr $size "$name"
       let addr+=$size
     done
     echo
@@ -391,64 +400,59 @@ case $1 in
     echo -e "kernel parameters:\n'`cat /proc/cmdline`'\n"
     $fw_printenv -n bootcmd |sed -n "s/\(.*\)/u-boot_env bootcmd:\n'\1'\n/p"
     $fw_printenv -n bootargs |sed -n "s/\(.*\)/u-boot_env bootargs:\n'\1'\n/p"
-    show_current_settings
+    current_configuration
     ;;
 
-  --tm*) ## set testmode [{off}]
-    [ "$2" == "off" ] \
-    && rm -fv /etc/default/$SELF.test \
-    || touch /etc/default/$SELF.test
-    exec $0 --
+  --tm*) ## enable testmode ...or disable '--tm off'
+    [ "$2" == "off" ] && rm -fv $TM_FILE || echo $2 >$TM_FILE; exec $0 --
     ;;
 
-  *-a) ## set either or both kernel/rootfs to '-a'
+  *-a) ## set kernel/rootfs to use '-a' images
     bootcmd_x auto
     if [ "kernel" == "${1:0:6}" ] || [ "-a" == "${1}" ]
     then
       kia=$( hexify $KIA+0 )
-      $fw_setenv bootcmd "nand read $UBM $kia $KIS; $BC_boot" && msg kernel-a is set
+      $fw_setenv bootcmd "nand read $UBM $kia $KIS; $BC_boot" && echo set kernel-a
     fi
     bootargs_x
     if [ "rootfs" == "${1:0:6}" ] || [ "-a" == "${1}" ]
     then
       let mtd=$RIP+0
       bootargs=$( $fw_printenv -n bootargs |sed "s/ubi.mtd=./ubi.mtd=$mtd/" )
-      $fw_setenv bootargs $bootargs && msg rootfs-a is set
+      $fw_setenv bootargs $bootargs && echo set rootfs-a
     fi
-    #echo && show_current_settings
     ;;
     
-  *-b) ## set either or both kernel/rootfs to '-b'
+  *-b) ## set kernel/rootfs to use '-b' images
     bootcmd_x auto
     if [ "kernel" == "${1:0:6}" ] || [ "-b" == "${1}" ]
     then
       kia=$( hexify $KIA+$KIS )
-      $fw_setenv bootcmd "nand read $UBM $kia $KIS; $BC_boot" && msg kernel-b is set
+      $fw_setenv bootcmd "nand read $UBM $kia $KIS; $BC_boot" && echo set kernel-b
     fi
     bootargs_x
     if [ "rootfs" == "${1:0:6}" ] || [ "-b" == "${1}" ]
     then
       let mtd=$RIP+1
       bootargs=$( $fw_printenv -n bootargs |sed "s/ubi.mtd=./ubi.mtd=$mtd/" )
-      $fw_setenv bootargs $bootargs && msg rootfs-b is set
+      $fw_setenv bootargs $bootargs && echo set rootfs-b
     fi
-    #echo && show_current_settings
     ;;
 
   --) ## affirm executable, version and mode
     echo $SELF v$VERSION ${tm:+testmode_active} && exit 0
     ;;
 
-  \?|-h|--help) # quick help
+  \?|-h|--help) # quick ref
+    echo "Quick reference...  (askerisk denotes variations of an option)"
     echo "Options:"
     sed -n 's/\(^  .*[a-z\*-]\)) ## \(.*\)/\1    \2/p' $0
     echo "Usage:"
     echo "  $SELF [option]"
     ;;
 
-   '') ## show current configuration
-    msg $( cat /etc/*-release 2>/dev/null )
-    show_current_settings
+  '') ## show current settings
+    current_configuration
     ;;
 
   *) # error
@@ -466,8 +470,6 @@ then
   "   $SELF --default help\n"
 fi
 
-[ -n "$tm" ] \
-&& echo "  ...remove '/etc/default/$SELF.test' to disable testmode, try: '--tm off'" \
-  >/dev/stderr
+${tm:-:} "  ...remove '$TM_FILE' to disable testmode, try: '--tm off'" >&2
 
 exit 0
